version: '3.8'

services:
  backend:
    build: ./simple-crud-api
    ports:
      - "5000:5000"
    env_file:
      - ./simple-crud-api/.env
    volumes:
      - ./simple-crud-api:/app
      - /app/node_modules
    depends_on:
      - frontend

  frontend:
    build: ./simple-crud-api-frontend
    ports:
      - "3000:3000"
    env_file:
      - ./simple-crud-api-frontend/.env
    volumes:
      - ./simple-crud-api-frontend:/app
      - /app/node_modules
